package com.example.quizapplication;

public class Questions {
    public String nQuestions[] = {
            "In case you see a vehicle that has met with an accident with injured passengers inside, you should -",
            "If a vehicle approaches a railway crossing that is not guarded and the vehicle wants to proceed, the driver should",
            "Transport vehicles can be distinguished by",
            "A learner’s license is valid for a period of",
            "Free passage should be provided to the following vehicles",
            "Vehicles that come from the opposite side should be allowed to proceed through the",
            "Driver of a vehicle can overtake when",
            "Zebra lines are meant for",
            "Red traffic light is an sign to",
            "Parking in front of a hospital is",
            "If a driver sees the sign for ‘slippery road ahead’, he/she must",
            "Drunken driving is",
            "Honking is prohibited near",
            "Rear view mirror is utilized for",
            "Pedestrians are not allowed to cross the road close to stopped vehicles or near sharp bends because",
            "Records needed for private vehicles are",
            "Validity of Pollution Under Control Certificate is",
            "Minimum age for availing a license to drive a motor vehicle without gear is",
            "Hand brake should be used to",
            "Minimum age to avail driving license for transport vehicles is",
            "If you are near a pedestrian crossing and there are people waiting to cross the road, you should",
            "You are coming towards a narrow bridge and another vehicle is about to enter the bridge from the other side. What should you do?",
            "When a long vehicle moves over to the right hand side of its lane, that means it…?",
            "A herdsman ahead of you is having trouble keeping his cows off the roadway. What should you do?",
            "When towing another vehicle, you must not exceed what speed?",
            "If a road has no pavement for pedestrians, what should they do?",
            "In which of these circumstances should you not attempt to make an overtake?",
            "The driver ahead puts their right arm out of the window pointing straight up, palm forwards. S/he is warning you that…?",
            "If you use your vehicle to obstruct a road as part of a protest or strike action, you can face…?",
            "When parking, you should make sure that there is at least how much space between your vehicle and those to the front and rear?",
            "By law, your registration plate should be illuminated with a light of which color?",
            "Which of these is the only one which it is not essential for the driver of a motor vehicle to have?",
            "What is the maximum number of people who can be carried on a two wheeled vehicle?",
            "You should not park within what distance of a fire hydrant?",
            "You are on a road which has no markings. When another vehicle approaches, you should…?",
            "A blinking red traffic light tells you that you must do what?",
            "The only type of horn permitted on a motor vehicle is what?",
            "If you approach an intersection where there is no policeman on duty and no signals, you should yield right-of-way to…?",
            "A triangular sign with a red border means what?",
            "Which of these colors is not permitted for private vehicles?",
            "When your driver's license expires, how long do you have to renew it?",
            "Under what circumstances is it permissible to undertake a vehicle on its left hand side?",
            "Which of these persons has a right to make you stop by signaling to you?",
            "When driving at night, you should…?",
            "Vehicles proceeding from opposite direction should be allowed to pass through ...",
            "You are approaching a narrow bridge, another vehicle is about to enter the bridge from opposite side you should",
            "Overtaking is prohibited in following circumstances",
            "Boarding in and alighting from a vehicle while in motion",
            "While turning to a road to the left of the road in which you are going, you should",
            "The Driver of a vehicle extends his right arm with the palm downward and moves the arm upward and downward several times. You will understand that",
            "One time tax for a new car is for how many years?",
            "You should keep to the left of the road when driving on single lane roads…?",
            "Where is a learner license valid?",
            "What is the minimum age for obtaining a permanent driving license for paid driving?",
            "When stopped at a junction controlled by traffic lights, you should watch…?",
            "Which of these is the correct order of things for making a turn?",
            "Before reversing your car, it's especially important…?",
            "Where on the roads do the most accidents occur?",
            "A blind pedestrian carrying a cane or accompanied by a guide dog has priority over motor vehicles where?",
            "On a three lane single carriageway, the middle lane is only for what?",
            "Carrying overload in goods carriages",
            "When you reach an intersection where there is no signal light or police man, you will",
            "According to section 129 of Motor Vehicle Act 1988 a person driving a motor cycle shall",
            "According to section 112 of the Motor Vehicles Act 1988",
            "Circumstances in which a motor cycle can be driven at the speed of 60 km/hour",
            "The only vehicle which is permitted to be driven at a speed exceeding 60 Km/hr",
            "What is meant by stop line?",
            "The number of passengers permitted to be taken in private vehicle is recorded in the",
            "All motor vehicles must be covered by",
            "When you hold a learners licence for motor cycle then"
            /*"",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",*/
    };

    private String nChoices[][] = {
            {"Take the vehicle to the closest police station and report the accident", "Take measures to secure medical attention to those injured and report the accident to the closest police station within a period of 24 hours", "Stop your vehicle and report the matter to the nearest police station"},
            {"Stop the vehicle on left hand side of the road, approach the track and ensure that there is no train or trolley coming from any side prior to crossing.", "Wait until the train passes", "Press horn and cross the track at the earliest"},
            {"The colour of the vehicle", "Number plate of the vehicle", "Tyre size of the vehicle"},
            {"30 days", "6 months", "Until a driving licence is availed"},
            {"Express buses", "Police vehicles", "Fire service vehicles and ambulance"},
            {"Left side", "Right side", "Any convenient side"},
            {"The driver of the vehicle ahead gives the signal to overtake", "Road is wide enough", "Driving down a hill"},
            {"Crossing of pedestrians", "Stopping vehicles", "Overtaking"},
            {"Slow the vehicle", "Stop the vehicle", "Proceed with caution"},
            {"Not correct", "Correct", "Depends on the situation"},
            {"Drive faster", "Change gear and reduce speed", "Apply brake but proceed in the same speed"},
            {"Allowed at night", "Allowed during the day", "Prohibited at all times"},
            {"Places of religious worship such as Temple, Mosque and Churches", "Hospitals, Court of Law", "Near Police Stations"},
            {"Watching traffic that is approaching from behind", "Watching back seat passengers", "Car decor"},
            {"It is an inconvenience to oncoming vehicles", "It is inconvenient to other pedestrians", "Drivers of approaching vehicles may not be able to see them"},
            {"G.C.R, Insurance Certificate, Registration Certificate", "Insurance Certificate, Registration Certificate, Driving License and Tax Token", "Permit, Trip Sheet, Registration Certificate"},
            {"1 year", "2 years", "6 months"},
            {"16 years", "21 years", "18 years"},
            {"Park a vehicle", "Apply brake suddenly", "Reduce speed"},
            {"16 years", "20 years", "45 years"},
            {"Press horn and proceed", "Stop the vehicle, wait until pedestrians cross and then move forward", "Slow down, press horn and proceed"},
            {"Wait until the other vehicle crosses the bridge before proceeding", "Switch on headlight and the cross the bridge", "Increase speed of the vehicle and try to cross the bridge quickly"},
            {"Is going to right", "Is going to left", "Could be turning left or right"},
            {"Rev your engine loudly", "Sound your horn and keep driving", "Slow down and prepare to stop if necessary"},
            {"36 km/h", "24 km/h", "28 km/h"},
            {"Walk on the right-hand side", "Walk on the left-hand side", "Walk in the center of the road"},
            {"On a bend", "When going uphill", "When it is raining"},
            {"They are turning right", "There is a police car ahead", "They are about to make a sudden stop"},
            {"A small fine", "Having your driving license suspended", "No action"},
            {"3 feet", "2 feet", "12 inches"},
            {"Yellow", "Red", "White"},
            {"Registration Certificate", "Tax Token", "Proof of Purchase"},
            {"One", "Two", "Three"},
            {"8 feet", "6 feet", "10 feet"},
            {"Let it pass on your left-hand side", "Let it pass on your right-hand side", "Hold the center of the road"},
            {"Slow down and proceed when safe", "Stop and proceed when safe", "Come to a stop immediately"},
            {"A single tone electric horn", "A single tone air horn", "A two tone electric horn"},
            {"Traffic coming from in front", "Traffic coming from your left", "Traffic coming from your right"},
            {"No parking", "Give way", "Speed restrictions end"},
            {"Olive Green", "Metallic Black", "Dark Blue"},
            {"90 days", "120 days", "30 days"},
            {"If it is turning right", "If there is a wide verge", "If it is going very slowly"},
            {"Traffic Wardens", "School crossing attendants", "Both A and B"},
            {"Drive at your normal daytime speed", "Reduce your normal daytime speed", "Any of these depending on the conditions"},
            {"Your right side", "Your left side", "The convenient side"},
            {"Increase the speed and try to cross the bridge as fast as possible", "Put on the head light and pass the bridge", "Wait till the other vehicle crosses the bridge and then proceed"},
            {"When it is likely to cause inconvenience or danger to other traffic", "When the vehicle in front is reducing speed", "During night"},
            {"Permitted in bus", "Permitted in auto-rickshaw", "Prohibited in all vehicles"},
            {"Show the left turn signal, drive to the center and turn to the left", "Sound horn and turn to the left", "Show the left turn signal, keep to the left side of the road and turn to the left"},
            {"The driver is turning to the left", "The driver is slowing down the vehicle", "The driver is allowing to overtake"},
            {"Till the registration of the vehicle is cancelled", "15 years", "5 years"},
            {"In urban areas", "During the monsoon", "In all normal circumstances"},
            {"Throughout India", "Only in the state of issue", "Throughout the world"},
            {"20", "18", "21"},
            {"Your light and the one to the right", "Your light and the one to the left", "Just your own light"},
            {"Signal - mirror - maneuver", "Mirror - signal - maneuver", "Maneuver - mirror - signal"},
            {"That you have checked your blind spot", "That you look in your rear side view mirror", "That you look in your left side view mirror"},
            {"Downhill roads", "Right-hand curves", "Intersections"},
            {"On single lane roads", "Everywhere", "On urban roads"},
            {"Turning left", "Turning right", "Overtaking and turning right"},
            {"Legally not punishable", "Only fine is attracted", "Can attract suspension or cancellation of driving licence"},
            {"Give way to traffic approaching the intersection from other roads", "Give proper signal, sound the horn and proceed", "Give way to the traffic approaching the intersection on your right side and proceed after giving necessary signals"},
            {"wear jerkins", "wear helmet", "wear shoes"},
            {"Speed limit shall not be exceeded", "Shall not drive after consuming alcohol", "Shall not use vehicle on road without paying tax"},
            {"During night", "During day time", "Under no circumstances"},
            {"Motor Cycle", "Motor Car", "Stage Carriage"},
            {"A line with 5 centimeters width in white or yellow colour at the approach of road junction or pedestrian crossing", "A line drawn through the center of the road in yellow colour", "A broken white line through the center of the road"},
            {"Registration Certificate", "Tax Token", "Permit"},
            {"Life Insurance", "Third party Insurance", "Comprehensive Insurance"},
            {"You will drive when the traffic is less", "You will drive the vehicle only when an instructor holding driving licence to drive motor cycle accompanies", "You will not carry any other person on the motor cycle except for the purpose of getting instructions from an instructor who holds a valid driving licence to drive motor cycle"},
            /*{"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},
            {"", "", ""},*/




    };

    private String nCorrectAnswers[] = {
            "Take measures to secure medical attention to those injured and report the accident to the closest police station within a period of 24 hours",
            "Stop the vehicle on left hand side of the road, approach the track and ensure that there is no train or trolley coming from any side prior to crossing.",
            "Number plate of the vehicle",
            "6 months",
            "Fire service vehicles and ambulance",
            "Right side",
            "The driver of the vehicle ahead gives the signal to overtake",
            "Crossing of pedestrians",
            "Stop the vehicle",
            "Not correct",
            "Change gear and reduce speed",
            "Prohibited at all times",
            "Hospitals, Court of Law",
            "Watching traffic that is approaching from behind",
            "Drivers of approaching vehicles may not be able to see them",
            "Insurance Certificate, Registration Certificate, Driving License and Tax Token",
            "6 months",
            "16 years",
            "Park a vehicle",
            "20 years",
            "Stop the vehicle, wait until pedestrians cross and then move forward",
            "Wait until the other vehicle crosses the bridge before proceeding",
            "Could be turning left or right",
            "Slow down and prepare to stop if necessary",
            "24 km/h",
            "Walk on the right-hand side",
            "On a bend",
            "They are about to make a sudden stop",
            "Having your driving license suspended",
            "3 feet",
            "White",
            "Proof of Purchase",
            "Two",
            "10 feet",
            "Let it pass on your right-hand side",
            "Stop and proceed when safe",
            "A single tone electric horn",
            "Traffic coming from your right",
            "Give way",
            "Olive Green",
            "30 days",
            "If it is turning right",
            "Both A and B",
            "Reduce your normal daytime speed",
            "Your right sideWait till the other vehicle crosses the bridge and then proceed",
            "When it is likely to cause inconvenience or danger to other traffic",
            "Prohibited in all vehicles",
            "Show the left turn signal, keep to the left side of the road and turn to the left",
            "The driver is slowing down the vehicle",
            "15 years",
            "In all normal circumstances",
            "Throughout India",
            "20",
            "Just your own light",
            "Mirror - signal - maneuver",
            "That you have checked your blind spot",
            "Intersections",
            "Everywhere",
            "Overtaking and turning right",
            "Can attract suspension or cancellation of driving licence",
            "Give way to the traffic approaching the intersection on your right side and proceed after giving necessary signals",
            "wear helmet",
            "Speed limit shall not be exceeded",
            "Under no circumstances",
            "Motor Car",
            "A line with 5 centimeters width in white or yellow colour at the approach of road junction or pedestrian crossing",
            "Registration Certificate",
            "Third party Insurance",
            "You will not carry any other person on the motor cycle except for the purpose of getting instructions from an instructor who holds a valid driving licence to drive motor cycle"
            /*"",
            "",
            "",
            "",
            "",*/


    };

    public String getQuestion(int a){
        String question = nQuestions[a];
        return question;
    }

    public String getChoice1(int a){
        String choice = nChoices[a][0];
        return choice;
    }

    public String getChoice2(int a){
        String choice = nChoices[a][1];
        return choice;
    }

    public String getChoice3(int a){
        String choice = nChoices[a][2];
        return choice;
    }

    public String getCorrectAnswer(int a){
        String answer = nCorrectAnswers[a];
        return answer;
    }
}
